name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "staging" ]  # Branche déclencheuse

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Deploy to Firebase
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project=secondes-avec-pst-d
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}